### ISSUE TITLE
Categories Not Filtering

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#30] opened 2016-10-20 19:38 UTC
Now that I've added more artists I am realizing that the categories are not actually filtering. When I choose Open Studios, 10 Central Avenue shows up, and when I choose different categories within it does not filter those either.

**Comment by macartscouncil** [comment] 2016-10-20 19:47
After looking again. The Sub Categories do work. The header categories, however, show everything until you click on a sub category. 

This is how it should work: 
Ex:
If you click on "Museums and Galleries" only items checked as "Museums and Galleries" should show up. Then the sub categories should operate from there.

**Comment by bekkblando** [comment] 2016-10-23 01:17
Is it every category or only Museums and Galleries(I've had problems with that one in particular in the past).

**Comment by macartscouncil** [comment] 2016-10-24 10:36
It was all of them from what I could tell.

**Comment by bekkblando** [comment] 2016-10-25 01:02
This should be resolved.  Please confirm.

**Comment by macartscouncil** [comment] 2016-10-25 13:22
If you go to Open Studios and then try to go to the next page it shows 10 Central Avenue still which is not in Open Studios. It also "un-highlights" Open Studios as if you are no longer on the category?

**Comment by bekkblando** [comment] 2016-11-05 04:16
I believe I've resolved this.  I'm going to do more testing in the morning.  It would be advantages to add some more artist to thoroughly test the pagination.

**Comment by macartscouncil** [comment] 2016-11-17 14:42
I will add more artists today.

**Comment by macartscouncil** [comment] 2016-11-17 15:20
The category "Jewelry and Glass" under both Visual Arts and Open Studios isn't showing artists who are checked as "Jewelry and Glass" 

Example artists: 
Purvi Ajmera
Kathy Young Albertelli

**Comment by macartscouncil** [comment] 2016-11-17 19:39
I'm also adding "Sculpture and Metal" and "Drawing and Paper Arts" to that list.

**Comment by bekkblando** [comment] 2016-11-19 16:06
I've added a fixed category for Sculpture and Metal and Jewelry and Glass.  

Currently, a misspelled duplicate of these two columns exists. I am removing it, but for immediate testing the correctly spelling can be selected.

**Closed as completed** 2016-11-22 22:27 UTC
Labels: bug
