### ISSUE TITLE
Main Website Menu Moving Down

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#2] opened 2016-05-03 17:36 UTC
When you shrink the screen in from full view the main menu for the website comes down and interferes with the "Greenville-Area Arts Directory Line"
![screenshot 2016-05-03 13 32 19](https://cloud.githubusercontent.com/assets/18532651/14992391/eafb0b3c-1133-11e6-9fe5-92fb9c4b40b2.png)

**Comment by bekkblando** [comment] 2016-05-09 00:26
This looks like a theme break point, meaning it may be a point of problem later.  The problem is resolved in this case.

-- Dev Notes
Fixed by adding margin-top: 165;

The main cause of this is a break of web standards on the part of the theme.  They should be changing to the hamburger at this break point, since it has to go to a new line.  Perhaps the theme does not dynamically handle the image.  

Most effective solution would be to either modify the theme to correct the standard or dynamically set the padding.

**Closed as completed by bekkblando** 2016-05-09 00:26 UTC
Labels: bug
